name: Cypress Tests

on:
  push:
    branches: [ main, feature, fix ]
  pull_request:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build containers
        run: docker compose build

      - name: Run tests:all
        run: docker compose up --abort-on-container-exit --exit-code-from cypress